baseURL = 'https://clsn.io/'
defaultContentLanguage = "zh-cn"
languageCode = 'zh-cn'
title = 'CLSN - 惨绿少年博客'
theme = "maupassant"
uglyurls = true
hasCJKLanguage = true   # 中日韩语言支持
enableRobotsTXT = true  # 爬虫支持
PaginatePath = "page"  # 分页
summaryLength = 140

# 伪静态
[permalinks]
  posts = ":slug"

[author]
    name = "惨绿少年"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives.html"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about.html"
    weight = 4

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params]
    localSearch = true
    busuanzi = true

[[params.links]]
  title = "惨绿少年(博客园)"
  name = "惨绿少年(博客园)"
  url = "http://clsn.cnblogs.com" 

[[params.links]]
  title = "Generate Ugly Avatar"
  name = "Generate Ugly Avatar"
  url = "http://ugly.shun.host" 
  
[[params.links]]
  title = "container-monitor"
  name = "container-monitor"
  url = "https://yasongxu.gitbook.io/container-monitor/" 

[params.utteranc]
    enable = true
    repo = "SummerShun/clsn.io"
    issueTerm = "pathname" # 表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
